apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-svc
  namespace: oidc-test
spec:
  selector:
    matchLabels:
      app: helloworld-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-svc
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: oidc-test
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: helloworld-svc

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-svc
  namespace: oidc-test
  annotations:
    plugins.konghq.com: oidc-kong-test1
spec:
  rules:
  - host: oidctest1.atlas.nonprod.torq.trans.apps.ge.com
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-svc
          servicePort: 80
      # - path: /api/v1
      #   backend:
      #     serviceName: helloworld-svc
      #     servicePort: 80
# ---
#
# apiVersion: configuration.konghq.com/v1
# kind: KongIngress
# metadata:
#   name: helloworld-svc
#   namespace: oidc-test
# route:
#   methods:
#   - POST
#   - GET
#   - PUT
#   - DELETE
#   - PATCH
#   - OPTIONS
#   preserve_host: true
#   protocols:
#   - http
#   - https
#   regex_priority: 0
#   strip_path: true
